"""Pure Yoga Deck domain contracts and transition policy."""

from .model import (
    ApplyRotation,
    CaptureText,
    Diagnostic,
    Effect,
    Event,
    InputRecoveryRequested,
    LaunchScratchpad,
    ManualOrientationRequested,
    MonitorTopologyChanged,
    Orientation,
    OrientationChanged,
    OrientationLockChanged,
    PenAction,
    PenActionRequested,
    ReconcileObservedState,
    ReconcileRequested,
    RefreshOskTheme,
    ResumeRequested,
    SetInternalInputsEnabled,
    SetOskEnabled,
    SettingsChanged,
    ShutdownRequested,
    State,
    TabletModeChanged,
    ThemeChanged,
    Transition,
)
from .reducer import reduce

__all__ = [
    "ApplyRotation",
    "CaptureText",
    "Diagnostic",
    "Effect",
    "Event",
    "ManualOrientationRequested",
    "MonitorTopologyChanged",
    "InputRecoveryRequested",
    "LaunchScratchpad",
    "Orientation",
    "OrientationChanged",
    "OrientationLockChanged",
    "PenAction",
    "PenActionRequested",
    "ReconcileObservedState",
    "ReconcileRequested",
    "RefreshOskTheme",
    "ResumeRequested",
    "SetInternalInputsEnabled",
    "SetOskEnabled",
    "ShutdownRequested",
    "State",
    "TabletModeChanged",
    "SettingsChanged",
    "ThemeChanged",
    "Transition",
    "reduce",
]
